export const AUDIT_ACTION_LABELS: Record<string, string> = {
  criar: "Criou",
  editar: "Editou",
  cancelar: "Cancelou",
  liquidar: "Liquidou (pagou/recebeu)",
  estornar: "Estornou",
  ativar: "Ativou",
  desativar: "Desativou",
  importar: "Importou",
  conciliar: "Conciliou",
  desfazer_conciliacao: "Desfez conciliação",
  ignorar: "Ignorou",
  reativar: "Reativou",
  gerar: "Gerou",
  enviar: "Enviou",
  exportar: "Exportou",
  conceder_permissao: "Concedeu permissão",
  revogar_permissao: "Revogou permissão",
  remover_override: "Removeu ajuste de permissão",
};

export const AUDIT_ENTITY_LABELS: Record<string, string> = {
  financial_entries: "Lançamento",
  financial_settlements: "Liquidação",
  transfers: "Transferência",
  installment_groups: "Parcelamento",
  recurring_rules: "Recorrência",
  chart_account_families: "Família (plano de contas)",
  chart_account_categories: "Categoria (plano de contas)",
  chart_account_subcategories: "Subcategoria (plano de contas)",
  cost_centers: "Centro de custo",
  bank_accounts: "Conta bancária",
  bank_balance_snapshots: "Saldo informado",
  counterparties: "Contraparte",
  payment_methods: "Forma de pagamento",
  import_batches: "Importação OFX",
  bank_transactions: "Transação bancária",
  rent_receipts: "Recibo de aluguel",
  report_configs: "Configuração de relatório",
  generated_reports: "Relatório gerado",
  organization_settings: "Configurações",
  profiles: "Usuário",
  user_permissions: "Permissão de usuário",
  exportacao: "Exportação",
  backup: "Backup",
};
